PACKAGE_NAME    = test-hello-sub
INSTALL_HEADERS = hello_sub.h

all: modules

clean: modules_clean

install: modules_install install_hdrs

include $(ENV_MAKE_DIR)/inc.env.mk
include $(ENV_MAKE_DIR)/inc.mod.mk
include $(ENV_MAKE_DIR)/inc.ins.mk
